[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
polyhedron-ops = { path = "./crates/polyhedron-ops" }
bevy = { version = "0.16" }
bevy_egui = { version = "0.35" }
bevy_panorbit_camera = { version = "0.27", features = ["bevy_egui"] }
ultraviolet = { version = "0.10", features = ["f64"] }
itertools = "0.14"
rayon = "1"

[patch.crates-io]
kiss3d = { git = "https://github.com/sebcrozet/kiss3d.git", branch = "master" }
